# Docker image, Azure Container Registry, and Azure Kubernetes Service
# Build a Docker image, push it to an Azure Container Registry, and deploy it to Azure Kubernetes Service.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # ========================================================================
  #                          Mandatory variables
  # ========================================================================

  # Update Azure.ResourceGroupName value with Azure resource group name.
  Azure.ResourceGroupName: devcluster

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnectionId: 'c5c98b92-7ae7-4ccd-a3d4-d48c4fbe0daf'

  # Update Azure.Location value with Azure Location.
  Azure.Location: 'eastus'

  # Update ACR.Name value with ACR name. Please note ACR names should be all lower-case and alphanumeric only.
  ACR.Name: 'finsights'

  # Update AKS.ClusterName value Azure kubernetes cluster name.
  AKS.ClusterName: 'kubernetes'

  # Docker Container port
  Container.Port: 80

  # ========================================================================
  #                           Optional variables
  # ========================================================================

  ACR.RepositoryName: 'lotusfinsightsgst'
  ACR.ImageName: '$(lotusfinsightsgst):$(Build.BuildId)'
  ACR.FullName: '$(finsigts).azurecr.io'
  ACR.Sku: 'Standard'
  AKS.KubeDeploymentYaml: '$(System.DefaultWorkingDirectory)/KubeDeployment.yml' # Update AKS.KubeDeploymentYaml if you want to use deployment file from repo instead of generated file.
  AKS.DeploymentPort: '443'
  Azure.CreateResources: 'true' # Update Azure.CreateResources to false if you have already created resources like resource group, azure container registry and azure kubernetes cluster.
  System.Debug: 'false'

jobs:

- job: CreateResources
  displayName: Create resources
  condition: and(succeeded(), eq(variables['Azure.CreateResources'], 'true'))

  pool:
    {{ pool }}

  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment:Create ACR and AKS'
    inputs:
      azureSubscription: 'azure finsights'
      resourceGroupName: 'dev cluster'
      location: 'east-us'
      templateLocation: 'URL of the file'
      addSpnToEnvironment: true
      csmFileLink: 'https://raw.githubusercontent.com/Microsoft/azure-pipelines-yaml/master/templates/resources/arm/aks.json'
      overrideParameters: '-registryName "$(ACR.Name)" -registryLocation "$(Azure.Location)" -servicePrincipalId $servicePrincipalId -servicePrincipalKey $servicePrincipalKey -clusterName "$(AKS.ClusterName)" -clusterLocation "$(Azure.Location)"'

- job: BuildImage
  displayName: Build
  dependsOn: CreateResources
  condition: or(succeeded(), ne(variables['Azure.CreateResources'], 'true'))

  pool:
    {{ pool }}

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: 'c5c98b92-7ae7-4ccd-a3d4-d48c4fbe0daf'
      azureContainerRegistry: 'finsights'
      imageName: 'bhargavlotusfinsights/lotus-finsights-gst'
      command: build
      dockerFile: '**/Dockerfile'

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      azureSubscriptionEndpoint: 'c5c98b92-7ae7-4ccd-a3d4-d48c4fbe0daf'
      azureContainerRegistry: 'finsights'
      imageName: 'bhargavlotuswireless/lotus-finsighs-gst'
      command: push

- job: DeployApp
  displayName: Deploy
  dependsOn: BuildImage
  condition: succeeded()

  pool:
    {{ pool }}

  steps:
  - bash: |
      if [ -f $(AKS.KubeDeploymentYaml) ]; then
        echo "##vso[task.setvariable variable=AKS.KubeDeploymentYamlExists;]true"
      else
        echo "##vso[task.setvariable variable=AKS.KubeDeploymentYamlExists;]false"
      fi
    displayName: 'Check kubernetes deployment yaml exists'

  - bash: |
       echo "apiVersion : apps/v1beta1
       kind: Deployment
       metadata:
         name: $(finsights)
       spec:
         replicas: 1
         template:
           metadata:
             labels:
               app: $(finsights)
           spec:
             containers:
             - name: $(lotus-finsights-gst)
               image: $bhargav lotus wireless/$lotus-finsights-gst
               ports:
               - containerPort: 80
       ---
       apiVersion: v1
       kind: Service
       metadata:
         name: finsights
       spec:
         type: LoadBalancer
         ports:
         - port: 80
         selector:
           app: finsights > $(AKS.KubeDeploymentYaml)
    displayName: 'deploy to kubernetes_release'
    condition: and(succeeded(), eq(variables['AKS.KubeDeploymentYamlExists'], 'False'))

  - task: Kubernetes@1
    displayName: 'kubectl apply'
    inputs:
      azureSubscriptionEndpoint: c5c98b92-7ae7-4ccd-a3d4-d48c4fbe0daf
      azureResourceGroup: Azure Finsights
      kubernetesCluster: kubernetes
      arguments: 'kubectl apply -f deployment.yaml,kubectl apply -f service.yaml"
      command: 'apply'
